//
//  LaunchModel.swift
//  spaceXLaunches
//
//  Created by Manson Jones on 3/24/20.
//  Copyright © 2020 Manson. All rights reserved.
//

import Foundation

struct Constants {
    static let missionNames =
        [
            "ABS-2A / Eutelsat 117W B",
            "ABS-3A / Eutelsat 115W B",
            "ANASIS-II",
            "Amos-17",
            "Amos-6",
            "ArabSat 6A",
            "AsiaSat 6",
            "AsiaSat 8",
            "Bangabandhu-1",
            "Boeing X-37B OTV-5",
            "BulgariaSat-1",
            "CASSIOPE",
            "CCtCap Demo Mission 1",
            "CCtCap Demo Mission 2",
            "COTS 1",
            "COTS 2",
            "CRS-1",
            "CRS-10",
            "CRS-11",
            "CRS-12",
            "CRS-13",
            "CRS-14",
            "CRS-15",
            "CRS-16",
            "CRS-17",
            "CRS-18",
            "CRS-19",
            "CRS-2",
            "CRS-20",
            "CRS-21",
            "CRS-3",
            "CRS-4",
            "CRS-5",
            "CRS-6",
            "CRS-7",
            "CRS-8",
            "CRS-9",
            "Crew Dragon In Flight Abort Test",
            "DSCOVR",
            "DemoSat",
            "EchoStar 23",
            "Es’hail 2",
            "Falcon 9 Test Flight",
            "Falcon Heavy Test Flight",
            "FalconSat",
            "FormoSat-5",
            "GPS III SV01",
            "GPS III SV03 (Columbus)",
            "GPS III SV04",
            "GPS SV05",
            "Hispasat 30W-6",
            "Inmarsat-5 F4",
            "Intelsat 35e",
            "Iridium NEXT Mission 1",
            "Iridium NEXT Mission 2",
            "Iridium NEXT Mission 3",
            "Iridium NEXT Mission 4",
            "Iridium NEXT Mission 5",
            "Iridium NEXT Mission 6",
            "Iridium NEXT Mission 7",
            "Iridium NEXT Mission 8",
            "JCSAT-16",
            "JCSAT-2B",
            "JCSat 18 / Kacific 1",
            "Jason 3",
            "KoreaSat 5A",
            "Merah Putih",
            "NROL-76",
            "Nusantara Satu (PSN-6) / S5 / Beresheet",
            "OG-2 Mission 1",
            "OG-2 Mission 2",
            "Paz / Starlink Demo",
            "RADARSAT Constellation",
            "RatSat",
            "RazakSat",
            "SAOCOM 1A",
            "SAOCOM 1B & Smallsat SSO Rideshare 1",
            "SES-10",
            "SES-11 / Echostar 105",
            "SES-12",
            "SES-16 / GovSat-1",
            "SES-8",
            "SES-9",
            "SSO-A",
            "STP-2",
            "SXM-7",
            "SXM-8",
            "Smallsat SSO Rideshare 2 (Mission 9)",
            "Starlink 1",
            "Starlink 2",
            "Starlink 3",
            "Starlink 4",
            "Starlink 5",
            "Starlink 6",
            "Starlink 7",
            "Starlink 8",
            "Starlink v0.9",
            "TESS",
            "Telstar 18V",
            "Telstar 19V",
            "Thaicom 6",
            "Thaicom 8",
            "Trailblazer",
            "Turksat 5A",
            "TürkmenÄlem 52°E / MonacoSAT",
            "USCV-1 (NASA Crew Flight 1)",
            "ZUMA"
    ]
    
    static let rocketNames = [
        "Falcon 1",
        "Falcon 9",
        "Falcon Heavy"
    ]
    
    static let launchYears = [Int](2006...2021).map { String($0) }
}

